# Generated by Django 5.2.4 on 2026-05-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_post_author_remove_post_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['-is_pinned', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='projectsection',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
