# Generated by Django 5.2.4 on 2026-05-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='is_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
