# Generated by Django 5.2.4 on 2026-06-02 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectsection_is_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Texto Simples'), ('question', 'Pergunta / Dúvida'), ('reference', 'Referência / Link')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='SectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='projects.projectsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
