# Generated by Django 6.0.6 on 2026-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_following'),
        ('projects', '0014_project_status_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='projects.project'),
        ),
    ]
