# Generated by Django 6.0.6 on 2026-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_report_options_remove_report_reporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Resolvido'), ('ignored', 'Ignorado')], default='pending', max_length=15),
        ),
    ]
